---
version: "2"
services:
  bookstack:
    image: linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=<yourdbpass>
      - DB_DATABASE=bookstackapp
    volumes:
      - /path/to/data:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=<yourdbpass>
      - TZ=Europe/London
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=<yourdbpass>
    volumes:
      - /path/to/data:/config
    restart: unless-stopped
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
      - PLEX_CLAIM= #optional
    volumes:
      - /path/to/library:/config
      - /path/to/tvseries:/tv
      - /path/to/movies:/movies
    restart: unless-stopped  
  plexpy:
    image: linuxserver/plexpy
    container_name: plexpy
    depends_on:
      - plex
    volumes:
      - /opt/appdata/plexpy:/config
      - /opt/appdata/plex/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro
    ports:
      - 27029:8181
    links:
      - plex
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    volumes:
      - /opt/appdata/nzbget/config:/config
      - /opt/downloads:/downloads
      - /mnt/disk1/downloads/complete:/downloads/complete
    ports:
      - 27020:6789
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    depends_on:
      - nzbget
    volumes:
      - /opt/appdata/sonarr:/config
      - /mnt/storage/tv:/tv
      - /mnt/disk1/downloads/complete/tv:/downloads
      - /mnt/storage/downloads/complete/tv_import:/tv_import
    ports:
      - 27021:8989
    links:
      - nzbget
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
  couchpotato:
    image: linuxserver/couchpotato
    container_name: couchpotato
    depends_on:
      - nzbget
    volumes:
      - /opt/appdata/couchpotato:/config
      - /mnt/disk1/downloads/complete/movies:/downloads
      - /mnt/storage/movies:/movies
    ports:
      - 27022:5050
    links:
      - nzbget
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: host
    volumes:
      - /opt/appdata/deluge:/config
      - /mnt/disk1/downloads:/downloads
      - /mnt/storage:/mnt/storage
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
  sync:
    image: linuxserver/resilio-sync
    container_name: sync
    volumes:
      - /opt/appdata/sync:/config
      - /mnt/storage:/sync
    ports:
      - 27028:8888
      - 55555:55555
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    restart: always
  smokeping:
    image: linuxserver/smokeping
    container_name: smokeping
    volumes:
      - /opt/appdata/smokeping/config:/config
      - /opt/appdata/smokeping/data:/data
    ports:
      - 27025:80
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    restart: always
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    volumes:
      - /opt/appdata/radarr:/config
      - /mnt/storage/movies:/movies
      - /mnt/disk1/downloads/complete/movies:/downloads
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    restart:
      always
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    ports:
      - 443:443
    volumes:
      - /opt/appdata/letsencrypt:/config
    restart:
      always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - EMAIL=some@email.com
      - URL=domain.tld
      - SUBDOMAINS=one,sub,domain,comma,separated
      - ONLY_SUBDOMAINS=true
      - DHLEVEL=4096
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    volumes:
      - /opt/appdata/influxdb:/var/lib/influxdb
    restart:
      always
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3001:3000
    volumes:
      - /opt/appdata/grafana:/var/lib/grafana
    restart:
      always
